# Generated by Django 3.0.2 on 2020-02-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200207_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AddField(
            model_name='history',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
