# Generated by Django 3.0.2 on 2020-02-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20200207_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='total_price',
            field=models.CharField(max_length=200),
        ),
    ]
