# Generated by Django 3.0.2 on 2020-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20200207_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='total_cart_price',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='total_price',
            field=models.CharField(max_length=20),
        ),
    ]
