# Generated by Django 3.0.2 on 2020-02-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20200208_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='address',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='history',
            name='pizza_list',
            field=models.CharField(max_length=400),
        ),
    ]
