# Generated by Django 3.0.2 on 2020-02-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20200208_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='total_price',
        ),
    ]
