# Generated by Django 3.0.2 on 2020-02-02 16:03

from django.db import migrations, models
import pp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='url',
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default=None, upload_to=pp.models.Post.upload_to),
        ),
    ]
