# Generated by Django 3.0.2 on 2020-02-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_auto_20200202_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.TextField(blank=True),
        ),
    ]
