# Generated by Django 3.0.2 on 2020-02-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0004_auto_20200204_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.TextField(blank=True, default=None),
        ),
    ]
