# Generated by Django 3.0.3 on 2020-02-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0005_auto_20200204_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
