# Generated by Django 3.0.3 on 2020-02-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0006_auto_20200218_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.TextField(blank=True, default=None),
        ),
    ]
